USE `CUSTOMER_DB`;
DROP procedure IF EXISTS `AMOUNT`;

DELIMITER $$
USE `CUSTOMER_DB`$$
CREATE PROCEDURE `AMOUNT` ()
BEGIN
	select CUST_NAME, GRADE FROM customer where OPENING_AMT+ RECEIVE_AMT >10000;
END$$

DELIMITER ;
